version: '3'
services:
  c-web:
    profiles:
    - single_host_cpu
    - single_host_gpu
    - central
    - central_with_inference_cpu
    - central_with_inference_gpu
    extends:
      file: docker-compose.common.yml
      service: x-web

  c-redis:
    profiles:
    - single_host_cpu
    - single_host_gpu
    extends:
      file: docker-compose.common.yml
      service: x-redis

  d-redis:
    profiles:
    - central
    - central_with_inference_cpu
    - central_with_inference_gpu
    extends:
      file: docker-compose.common.yml
      service: x-redis
    ports:
    - "${REDIS_PORT}:${REDIS_PORT}"

  c-ui:
    profiles:
    - single_host_cpu
    - single_host_gpu
    - central
    - central_with_inference_cpu
    - central_with_inference_gpu
    extends:
      file: docker-compose.common.yml
      service: x-ui

  c-signaling:
    profiles:
    - single_host_cpu
    - single_host_gpu
    - central
    - central_with_inference_cpu
    - central_with_inference_gpu
    extends:
      file: docker-compose.common.yml
      service: x-signaling

  c-mediabridge:
    profiles:
    - single_host_cpu
    - single_host_gpu
    - central
    - central_with_inference_cpu
    - central_with_inference_gpu
    extends:
      file: docker-compose.common.yml
      service: x-mediabridge
    deploy:
      replicas: 1
      

  c-inference:
    profiles:
    - single_host_cpu
    - central_with_inference_cpu
    extends:
      file: docker-compose.common.yml
      service: x-inference
    deploy:
      replicas: 5

  cgpu-inference:
    profiles:
    - single_host_gpu
    - central_with_inference_gpu
    extends:
      file: docker-compose.common.yml
      service: x-gpu-inference
    deploy:
      replicas: 1

  d-inference:
    profiles:
    - inference_cpu
    extends:
      file: docker-compose.common.yml
      service: x-inference
    deploy:
      replicas: 10

  dgpu-inference:
    profiles:
    - inference_gpu
    extends:
      file: docker-compose.common.yml
      service: x-gpu-inference
    deploy:
      replicas: 1
