version: '3'
services:
  c-web:
    profiles:
    - single_host
    - central
    - central_with_inference
    extends:
      file: docker-compose.common.yml
      service: x-web

  c-redis:
    profiles:
    - single_host
    extends:
      file: docker-compose.common.yml
      service: x-redis

  d-redis:
    profiles:
    - central
    - central_with_inference
    extends:
      file: docker-compose.common.yml
      service: x-redis
    ports:
    - "${REDIS_PORT}:${REDIS_PORT}"

  c-ui:
    profiles:
    - single_host
    - central
    - central_with_inference
    extends:
      file: docker-compose.common.yml
      service: x-ui

  c-signaling:
    profiles:
    - single_host
    - central
    - central_with_inference
    extends:
      file: docker-compose.common.yml
      service: x-signaling

  c-mediabridge:
    profiles:
    - single_host
    - central
    - central_with_inference
    extends:
      file: docker-compose.common.yml
      service: x-mediabridge
    deploy:
      replicas: 1
      

  c-inference:
    profiles:
    - single_host
    - central_with_inference
    extends:
      file: docker-compose.common.yml
      service: x-inference
    deploy:
      replicas: 5

  d-inference:
    profiles:
    - inference
    extends:
      file: docker-compose.common.yml
      service: x-inference
    deploy:
      replicas: 10
