{
 "title": "Distributed Inference Dashboard",
 "description": "Docker and Inference Metrics with influx, Telegraf and Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "Docker_Stack",
    "label": "Docker_Stack",
    "query": "SHOW TAG VALUES WITH KEY = \"docker.group\"  "
   },
   {
    "name": "DS_INFLUXDB",
    "query": "distributed-inference-influxdb-influxql"
   }
  ]
 },
 "panels": [
  {
   "title": "Inference - Frames per Second (by Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_host | $tag_instance ($tag_task)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "inference_time_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Inference - Frames per Second (Current)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host | $tag_instance ($tag_task)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "task" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "prometheus_remote_write",
     "select": [
      [
       { "params": [ "inference_time_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host | $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Docker Status",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "running" ], "type": "alias" }
      ],
      [
       { "params": [ "n_containers_paused" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "paused" ], "type": "alias" }
      ],
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "stopped" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mem Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host | $tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host | $tag_container_name RX traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_container_name TX traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host | $tag_container_name IO_write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_write"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    },
    {
     "alias": "$tag_host | $tag_container_name IO_read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_read"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  }
 ]
}